version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/projects/Plant_Project
    
hooks:
  AfterInstall:
    # location은 프로젝트의 root경로를 기준
    - location: deploy.sh
      timeout: 180
      runas: root
